name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (optional)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version if needed

      - name: Run a basic HTML check
        run: |
          echo "Running HTML validation..."
          npx htmlhint your-file.html  # Replace with the actual HTML file path
          
      - name: Deploy (optional)
        run: |
          echo "Deploying the application..."
          # Add your deployment steps here (e.g., using GitHub Pages or another service)

      - name: Notify
        run: |
          echo "Build completed successfully!"
